
import NavBar from './components/Navbar'
import {Roboto} from 'next/font/google'
import   '@/app/globals.css'

const fuenteAqui=Roboto({weight:["400","500","700"],
    styles:["italic","normal"],
    subsets:["latin"]
})

export const metadata = {
    title: 'next.js',
    description: 'generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <title>App de david</title>
            <body className={fuenteAqui.className}>
           <NavBar/>
           {children}
           </body>
        </html>
    )
}